version: "3"
services:
  #DATABASE SERVICE
  mysql:
    image: mysql
    container_name: phptutorial_db
    ports:
      - 33061:3306
    environment:
      MYSQL_DATABASE: phptutorial_db
      MYSQL_ROOT_PASSWORD: root

  #APPLICATION SERVICE
  php:
    image: phptutorial_app
    container_name: phptutorial_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      CONTAINER_ROLE: phptutorial_app

  #NGINX SERVICE
  nginx:
    image: nginx:alpine
    container_name: phptutorial_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    ports:
      - 8090:80